appserver:
  name: appserver
  replicas: 1

  image:
    name: appserver
    tag: latest
    port: 3000

  service:
    name: app-server-clusterip-service
    type: ClusterIP

userservice:
  name: user-service
  replicas: 1

  image:
    name: userservice
    tag: latest
    port: 4000

  service:
    name: user-service-clusterip-service
    type: ClusterIP
