apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-service
spec:
  ingressClassName: nginx
  rules:
    - host: public.app-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-server-clusterip-service
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-service
spec:
  ingressClassName: nginx
  rules:
    - host: public.user-service.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-service-clusterip-service
                port:
                  number: 4000
---

